function headers = load_scardec_headers(filename, startRow, endRow)
% Load the source parameters in the original format directly downloaded from SCARDEC website
% Modified from the Matlab automatically generated import function
% ==================================================================
% IMPORTFILE Import numeric data from a text file as a matrix.
%   FCTMOYSOURCE20161018163641SOUTHOFFIJIISLANDS = IMPORTFILE(FILENAME)
%   Reads data from text file FILENAME for the default selection.
%
%   FCTMOYSOURCE20161018163641SOUTHOFFIJIISLANDS = IMPORTFILE(FILENAME,
%   STARTROW, ENDROW) Reads data from rows STARTROW through ENDROW of text
%   file FILENAME.
%
% Example:
%   fctmoysource20161018163641SOUTHOFFIJIISLANDS = importfile('fctmoysource_20161018_163641_SOUTH_OF_FIJI_ISLANDS', 1, 2);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2019/09/04 21:18:41

%% Initialize variables.
delimiter = ' ';
if nargin<=2
    startRow = 1;
    endRow = 2;
end

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
headers0 = [dataArray{1:end-1}];
headers = zeros(1,17);
headers(1:8)=headers0(1,1:8);
headers(9:17)=headers0(2,:);
end