function [T, STF] = read_stfs(filename)
%IMPORTFILE Import data from a text file
%  FCTMOYSOURCE19920206011238SOUTHERNSUMATRAINDONESIA =
%  IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the numeric data.
%
%  FCTMOYSOURCE19920206011238SOUTHERNSUMATRAINDONESIA = IMPORTFILE(FILE,
%  DATALINES) reads data for the specified row interval(s) of text file
%  FILENAME. Specify DATALINES as a positive scalar integer or a N-by-2
%  array of positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  fctmoysource19920206011238SOUTHERNSUMATRAINDONESIA = importfile("/Users/Yin9xun/Dropbox/SCARDEC_STFs/sourcefunction_archive_1616417395/FCTs_19920206_011238_SOUTHERN_SUMATRA__INDONESIA/fctmoysource_19920206_011238_SOUTHERN_SUMATRA__INDONESIA", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-Jun-2019 10:18:02

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11"];
opts.SelectedVariableNames = ["VarName1", "VarName2"];
opts.VariableTypes = ["double", "double", "string", "string", "string", "string", "string", "string", "string", "string", "string"];
opts = setvaropts(opts, [3, 4, 5, 6, 7, 8, 9, 10, 11], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 2], "TrimNonNumeric", true);
opts = setvaropts(opts, [1, 2], "ThousandsSeparator", ",");
opts = setvaropts(opts, [3, 4, 5, 6, 7, 8, 9, 10, 11], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Import the data
STF_M = readtable(filename, opts);

%% Convert to output type
STF_M = table2array(STF_M);

T = STF_M(:,1);
STF = STF_M(:,2);
end