function headers = read_headers(filename)
%IMPORTFILE Import data from a text file
%  FCTMOYSOURCE19920206011238SOUTHERNSUMATRAINDONESIA =
%  IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the numeric data.
%
%  FCTMOYSOURCE19920206011238SOUTHERNSUMATRAINDONESIA = IMPORTFILE(FILE,
%  DATALINES) reads data for the specified row interval(s) of text file
%  FILENAME. Specify DATALINES as a positive scalar integer or a N-by-2
%  array of positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  fctmoysource19920206011238SOUTHERNSUMATRAINDONESIA = importfile("/Users/Yin9xun/Dropbox/SCARDEC_STFs/sourcefunction_archive_1616417395/FCTs_19920206_011238_SOUTHERN_SUMATRA__INDONESIA/fctmoysource_19920206_011238_SOUTHERN_SUMATRA__INDONESIA", [1, 2]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-Jun-2019 10:12:55

%% Input handlinga

% If dataLines is not specified, define defaults

dataLines = [1, 2];


%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "Var10", "Var11"];
opts.SelectedVariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "string"];
opts = setvaropts(opts, [10, 11], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 2, 6, 7, 8], "TrimNonNumeric", true);
opts = setvaropts(opts, [1, 2, 6, 7, 8], "ThousandsSeparator", ",");
opts = setvaropts(opts, [10, 11], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Import the data
headers0 = readtable(filename, opts);

%% Convert to output type
headers0 = table2array(headers0);

headers = zeros(1,17);
headers(1:8) = headers0(1,1:8);
headers(9:end)=headers0(2,:);

end